#!/bin/bash
set -e

SCRIPT=$1
INPUT=$2
OUTPUT=$3

EXE="test_matcher"

if [ $# -le 1 ]; then
  echo "escuuse me ... try instead"
  echo "docker run -it -v $PWD:/mnt/data docker.internal.adroll.com:5000/bi/trck cool.tr input.tdb [output.csv]" >&2
  exit 1
fi

trck -c $SCRIPT -o $EXE >/dev/null
(>&2 echo "tr compiled succesfully ")

if [ $OUTPUT ]
then 
 ./$EXE $INPUT > $OUTPUT 2>/dev/null
 (>&2 echo "trck query finished ")
else
  ./$EXE $INPUT 2>/dev/null
  (>&2 echo "did you memorize all that?")
fi

rm $EXE 
