#!/bin/bash
set -e

SCRIPT=$1
INPUT=$2
OUTPUT=$3

if [ "$#" -le 2 ]; then
  echo "escuuse me ... try instead"
  echo "docker run -it -v $PWD:/mnt/data docker.internal.adroll.com:5000/bi/trck cool.tr input.tdb [output.csv]" >&2
  exit 1
fi

trck -c $SCRIPT -o test_matcher >/dev/null
(>&2 echo "tr compiled succesfully ... you do not suck")

if [ $OUTPUT ]
then 
 ./test_matcher $INPUT > $OUTPUT
 (>&2 echo "trck query finished ... hope you are happy")
else
  ./test_matcher $INPUT
  (>&2 echo "did you memorize all that?")
fi
